---
# Instalar y administrar DNS Server maestro

- name: instalar service
  yum:
    name: bind
    state: present
  tags: install

- name: Configurar DNS maestro
  template: 
    src: named.conf.master.j2 
    dest: /etc/named.conf 
    owner: root
    group: named
    mode: '640'
  notify: restart named
  tags: 
    -  master

- name: Configurar DNS esclavo
  template: 
    src: named.conf.slave.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '640'
  notify: restart named
  tags: 
    -  slave

- name: Crear directorio de Zonas
  file:
    path: /etc/named/zones
    state: directory
    owner: root
    group: named
    mode: 0750
  tags: 
    -  master

- name: Crear directorio de Zonas
  file:
    path: /etc/named/cache
    state: directory
    owner: root
    group: named
    mode: 0750
  tags:
    -  slave

- name: Permitir modificaciones en el directorio /etc/named/cache
  sefcontext:
    target: '/etc/named/cache'
    setype: named_cache_t
    state: present
  tags:
    - slave

- name: Crear dominio {{ zoneDomain }}
  template:
    src: '{{ item }}.zone.j2'
    dest: '/etc/named/zones/{{ item }}.zone'
    owner: root
    group: named
    mode: 0640
  with_items: '{{ zoneDomain }}'
  notify: restart named
  tags: 
    -  master

- name: Empezar servicio de firewall.
  service:
    name: firewalld
    state: started
  tags: install

- name: abrir puerto
  firewalld:
    service: dns
    zone: 'public'
    permanent: true
    state: enabled
    immediate: yes
  tags: install

- name: Crear dominio {{ subDomain }}
  template:
    src: '{{ item }}.zone.j2'
    dest: '/etc/named/zones/{{ item }}.zone'
    owner: root
    group: named
    mode: 0640
  with_items: '{{ subDomain }}'
  notify: restart named
  tags:
    -  subdomain

